"""
Core schemas for the Deep Research Agent.

These Pydantic models define the structured data that moves
through the research system, including evidence-backed
findings in the final report.
"""

from pydantic import BaseModel, Field


class ResearchQuestion(BaseModel):
    """
    A research question created by the planner or
    adaptive research planner.
    """

    question: str = Field(
        description="A specific research question to investigate."
    )

    search_queries: list[str] = Field(
        default_factory=list,
        description="Search queries that can help answer the question.",
    )

    parent_question_number: int | None = Field(
        default=None,
        description=(
            "1-based number of the original research question "
            "that this question is a follow-up to. "
            "None for original planner questions."
        ),
    )


class Source(BaseModel):
    """
    A web source discovered during research.
    """

    url: str = Field(
        description="The URL of the source."
    )

    title: str = Field(
        default="",
        description="Title of the source.",
    )

    content: str = Field(
        default="",
        description="Relevant extracted content from the source.",
    )


class Evidence(BaseModel):
    """
    A verified piece of evidence extracted from a source.

    Its position in the verified evidence list can be used
    as an evidence reference in the final report.
    """

    research_question_number: int = Field(
        description=(
            "1-based number of the research question "
            "this evidence supports."
        )
    )

    claim: str = Field(
        description="The factual claim supported by the evidence."
    )

    source_url: str = Field(
        description="URL of the source supporting the claim."
    )

    supporting_text: str = Field(
        description="Text from the source that supports the claim."
    )


class ResearchFinding(BaseModel):
    """
    A factual finding in the final report.

    Evidence references point to 1-based positions in the
    verified evidence list supplied to the synthesizer.
    """

    text: str = Field(
        description="A concise, evidence-supported research finding."
    )

    research_question_numbers: list[int] = Field(
        default_factory=list,
        description=(
            "1-based numbers of the original research questions "
            "this finding helps answer."
        ),
    )

    evidence_numbers: list[int] = Field(
        min_length=1,
        description=(
            "1-based positions of verified evidence items that "
            "directly support this finding."
        ),
    )


class ResearchReport(BaseModel):
    """
    Final structured research report.

    Finding citations reference verified evidence rather than
    relying on URLs generated by the language model.
    """

    title: str = Field(
        description="Title of the research report."
    )

    summary: str = Field(
        description="Concise summary of the research findings."
    )

    findings: list[ResearchFinding] = Field(
        default_factory=list,
        description=(
            "Important findings, each linked to the research "
            "questions it addresses and the evidence supporting it."
        ),
    )

    sources: list[str] = Field(
        default_factory=list,
        description=(
            "Source URLs populated deterministically from verified "
            "evidence, rather than generated by the language model."
        ),
    )
