"""
Planner node for the Deep Research Agent.

The planner converts the user's broad research question
into a list of specific, actionable research questions.
"""

import os

from dotenv import load_dotenv
from langchain_core.prompts import ChatPromptTemplate
from langchain_ollama import ChatOllama
from pydantic import BaseModel, Field

from app.graph.state import ResearchState
from app.schemas.research import ResearchQuestion


load_dotenv()


MODEL_NAME = os.getenv(
    "OLLAMA_MODEL",
    "qwen2.5-coder:7b",
)

BASE_URL = os.getenv(
    "OLLAMA_BASE_URL",
    "http://localhost:11434",
)


model = ChatOllama(
    model=MODEL_NAME,
    base_url=BASE_URL,
    temperature=0,
)


class ResearchPlanOutput(BaseModel):
    """
    Structured output generated by the planner.
    """

    research_questions: list[ResearchQuestion] = Field(
        description=(
            "Specific research questions that should be "
            "investigated to answer the user's main question."
        )
    )


structured_model = model.with_structured_output(
    ResearchPlanOutput
)


prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            """
You are the planning component of a deep research agent.

Break the user's broad research question into several
specific questions that can be investigated independently.

For every research question:

1. Make it specific and factual.
2. Make sure it contributes directly to the main question.
3. Provide useful web search queries.
4. Avoid duplicate questions.

Create between 3 and 5 research questions.

Return only the requested structured output.
""",
        ),
        (
            "human",
            """
Main research question:

{question}
""",
        ),
    ]
)


chain = prompt | structured_model


def planner_node(
    state: ResearchState,
) -> ResearchState:
    """
    Generate the research plan and store it in state.
    """

    print("\n[Node] planner")

    response = chain.invoke(
        {
            "question": state["question"],
        }
    )

    research_questions = response.research_questions

    print(
        f"Generated {len(research_questions)} "
        "research questions."
    )

    return {
        **state,
        "research_questions": research_questions,
        "current_question_index": 0,
        "research_complete": False,
    }
